# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User

bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds
# bind = Super+Shift+M, exec
# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

# Custom Keybinds for moving workspace
bind = Super+Shift, code:10, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 1 # [hidden]
bind = Super+Shift, code:11, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 2 # [hidden]
bind = Super+Shift, code:12, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 3 # [hidden]
bind = Super+Shift, code:13, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 4 # [hidden]
bind = Super+Shift, code:14, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 5 # [hidden]
bind = Super+Shift, code:15, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 6 # [hidden]
bind = Super+Shift, code:16, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 7 # [hidden]
bind = Super+Shift, code:17, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 8 # [hidden]
bind = Super+Shift, code:18, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 9 # [hidden]
bind = Super+Shift, code:19, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 10 # [hidden]
# keypad numbers
bind = Super+Shift, code:87, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 1  # [hidden]
bind = Super+Shift, code:88, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 2  # [hidden]
bind = Super+Shift, code:89, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 3  # [hidden]
bind = Super+Shift, code:83, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 4  # [hidden]
bind = Super+Shift, code:84, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 5  # [hidden]
bind = Super+Shift, code:85, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 6  # [hidden]
bind = Super+Shift, code:79, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 7  # [hidden]
bind = Super+Shift, code:80, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 8  # [hidden]
bind = Super+Shift, code:81, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 9  # [hidden]
bind = Super+Shift, code:90, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspace 10 # [hidden]

# Moving inside one workspace
# Cycle windows; if floating bring to top
bindd = ALT, tab, cycle next window, cyclenext
bindd = ALT, tab, bring active to top, bringactivetotop

# Move back and forth between last two workspaces
bindd = SUPER, tab, workspace back and forth, movetoworkspace, previous

bindd = CTRL+SUPER, M, open spotify in special workspace, exec, sh -c '! hyprctl -j workspaces | grep -q "\"name\": \"spotify\"" && hyprctl dispatch togglespecialworkspace spotify && pgrep -x spotify >/dev/null || spotify-launcher || hyprctl dispatch togglespecialworkspace spotify'
bindd = CTRL+SUPER, D, open special workspace, togglespecialworkspace, special


bindd = CTRL+SHIFT, G, open a window group, togglegroup
